services:
  acerola_db:
    image: postgres:16.1-alpine3.19
    container_name: acerola_db
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  acerola:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acerola
    env_file:
      - .env
    volumes:
      - gems:/usr/local/bundle
      - .:/acerola
    ports:
      - '9292:9292'
    depends_on:
      - acerola_db

volumes:
  PGDATA:
  gems:

networks:
  default:
    name: acerola_network
