services:
  acerola_db:
    image: postgres:16.1-alpine3.19
    container_name: acerola_db
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  acerola01: &acerola01
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acerola01
    volumes:
      - gems:/usr/local/bundle
      - .:/acerola
    depends_on:
      - acerola_db
  acerola02:
    <<: *acerola01
    container_name: acerola02
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - acerola01
      - acerola02
    ports:
      - '9999:9999'

volumes:
  gems:
